[tool.poetry]
name = "algo-trading-notes"
version = "0.1.0"
description = ""
authors = ["hy"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.2.0"
scipy = "^1.12.0"
numpy = "^1.26.3"
scikit-learn = "^1.4.0"
yfinance = "^0.2.36"
ipykernel = "^6.29.0"
python-dotenv = "^1.0.1"
quandl = "^3.7.0"
eikon = "^1.1.18"
seaborn = "^0.13.1"
mplfinance = "^0.12.10b0"
plotly = "^5.18.0"
nbformat = "^5.9.2"
<<<<<<< Updated upstream
pyarrow = "^15.0.0"
openpyxl = "^3.1.2"
=======
statsmodels = "^0.14.1"
>>>>>>> Stashed changes


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
